### ISSUE TITLE
Identify dependencies in readme

### ISSUE THREAD

**Issue by josefnpat** [MisterDA/love-release#16]
I went to use love-release, and found that I don't have `getopt` or `getoptex` and I'm not sure it's available on arch linux.

Perhaps you could link to the project page, so that folks know it's a dependency?

    ~/repos/love-release♠ ./love-release.sh 
    ./love-release.sh: line 136: /include/getopt/getopt.sh: No such file or directory
    ./love-release.sh: line 137: getoptex: command not found
    ./love-release.sh: line 177: getoptex: command not found
    ./love-release.sh: line 211: shift: -1: shift count out of range
    ./love-release.sh: line 292: getoptex: command not found
    ./love-release.sh: missing operands.
    love-release.sh [-adlmw] [-n project_name] [-r release_dir] [-v love_version] [FILES...]
    Try 'love-release.sh --help' for more information.
    ~/repos/love-release♠ pacman ^C
    ~/repos/love-release♠ pacman -S getopt
    error: you cannot perform this operation unless you are root.
    ~/repos/love-release♠ sudo pacman -S getopt
    [sudo] password for seppi: 
    error: target not found: getopt
    ~/repos/love-release♠ pacman -Ss getopt
    core/perl 5.20.1-1 (base) [installed]
        A highly capable, feature-rich programming language
    community/gambas3-gb-option 3.6.2-1 (gambas3)
        Getopt component
    community/lua-alt-getopt 0.7.0-5
        Lua module for processing options similar to getopt_long(3) (5.1)
    community/lua51-alt-getopt 0.7.0-5
        Lua module for processing options similar to getopt_long(3) (5.1)
    community/perl-getopt-argvfile 1.11-7
        Take options from files

**Comment by MisterDA** [comment]
Well, I was trying to get long arguments in a bash script. The standard getopt doesn't support it. There are plenty of questions, examples, tutorials on the net but none was really giving a working solution.
I've found [a script](http://www.opensource.apple.com/source/bash/bash-76.1/bash/examples/functions/getoptx.bash), called getoptex, which goes back to 1997 (wow), and I've also copied it as a [Gist](https://gist.github.com/MisterDA/7284755). It works, but is quite old. Bash has been around here for quite a time, and I don't see why getoptex would not work. The script is still part of Ubuntu's bash-doc pkg, if I remember well.

There is another dependancy, the [Bash-INI parser](https://github.com/rudimeier/bash_ini_parser) I use.

I was wondering on how to add theses to the main script. There's no way to be shure getoptex is installed. I had the option to embed it whithin the script, or to let it seperate and to download it, same for the parser.

That's why I wrote the [install.sh](https://github.com/MisterDA/love-release/blob/master/install.sh) script. It normally should download getoptex and the parser, as well as put love-release.sh, the scripts, the manpage, the completion into the standards locations. It also searches/replaces certain files locations stored in the manpage and in love-release.sh to match the installation's location. It even knows where to install itself, if you're running as root or as a non-priviledged user.

Is there a better way to do this ? Ask the user to install by hand the two scripts ? Use git submodule ? Not realy sure about how it works, and if it would be really usefull here. And I don't give much credit to the author of the parser, nor getoptex, which I'm not proud of.

Finally, I don't know where the error you've encountered comes from. Perhaps you haven't been using the install.sh script ? It's been here since August :)

Other depedencies:
- [curl](http://curl.haxx.se/)
- [zip](http://www.info-zip.org/Zip.html), [unzip](http://www.info-zip.org/UnZip.html)
- [lua](http://www.lua.org/) (optional)
- [wine](http://www.winehq.com/) (optional)

**Comment by MisterDA** [comment]
Buuut I've just found out there's a much more simpler script like getoptex... It's part of ArchLinux' [util-linux](https://www.archlinux.org/packages/core/x86_64/util-linux/). Reliable, and certainly adopted everywhere.
`/usr/share/doc/util-linux/examples/getopt-parse.bash` ([Gist](https://gist.github.com/MisterDA/638605478d8e055f073b))
It seems to have the same features, while beeing far simpler than the old one. I need to dig in.

**Comment by josefnpat** [comment]
I don't want to "install" the `getoptex` function, unless it's through my **package manager**. If you want your software to depend on such a vague script, I would suggest using it from the cloned repository, as opposed to installing it in `.local` or `.share`.

The idea of having an "install" script that installs to my root or home folder does not comfort me. While I understand the need to have a workspace (e.g. `.local/love-release`) I do not like the idea of core components of the software being installed into them.

**Comment by MisterDA** [comment]
Are you saying that you would prefer the sub-scripts (getopt, ini parser, platform-scripts) to be splitted while developing, but concatenated  into one big script for regular use ?

**Comment by josefnpat** [comment]
I don't see why not release a set of scripts that represent love-release. I mean, CVS was initially just a set of scripts as well!

**Comment by MisterDA** [comment]
Well I'm sorry, but I don't really see what you mean and what is your idea on how love-release should be...

**Comment by josefnpat** [comment]
if `love-release` would become a unix/linux tool (which would be **awesome**) that could be incorporated into the package manager, `getopex` should be a dependency that should be installed by the package manager as opposed into `~/.love-release` or `/usr/share/love-release`, IMO.

The mere fact that you attempt want to use [`getoptex` as a script that is expected to be in the user path](https://github.com/MisterDA/love-release/blob/master/love-release.sh#L137) should be evidence that it should be a dependency.

I would suggest either:

1. asking users to install `getoptex` (provide instructions if none exist. e.g. `cp getoptex.sh /usr/bin/getoptex` and have the script check for `getoptex` in the user's path.

  Perhaps create the `getoptex` package for ubuntu and other common OS's. I'd be willing to maintain the Arch linux AUR version if you like!

2. putting `getoptex.sh` into the repository, and referencing it like this:

  `while $LOVE_RELEASE_DIR/getoptex.sh "$SCRIPT_ARGS" "$@"`

3. Find a workaround with `getopt` and identify the dependency if it is uncommon (on arch it is a part of `util-linux`, so it's common.)

This would remove the need for the `install.sh` script altogether, and it would be a lot easier for users to use!

__As a side note, `bash-doc` on ubuntu 14.04 does not provide `getoptex`.__

    ~♠ getoptex
    getoptex: command not found
    ~♠ sudo apt-get install bash-doc 
    [sudo] password for seppi: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libdbi1 librrd4 ntop-data python-mako python-markupsafe
    Use 'apt-get autoremove' to remove them.
    The following NEW packages will be installed:
      bash-doc
    0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
    Need to get 1,120 kB of archives.
    After this operation, 2,647 kB of additional disk space will be used.
    Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main bash-doc all 4.3-7ubuntu1.5 [1,120 kB]
    Fetched 1,120 kB in 1s (1,006 kB/s) 
    Selecting previously unselected package bash-doc.
    (Reading database ... 195435 files and directories currently installed.)
    Preparing to unpack .../bash-doc_4.3-7ubuntu1.5_all.deb ...
    Unpacking bash-doc (4.3-7ubuntu1.5) ...
    Processing triggers for doc-base (0.10.5) ...
    Processing 2 added doc-base files...
    Registering documents with scrollkeeper...
    Processing triggers for install-info (5.2.0.dfsg.1-2) ...
    Setting up bash-doc (4.3-7ubuntu1.5) ...
    ~♠ getoptex
    getoptex: command not found

I apologize if my demeanor was crude earlier, it was very late. I really like this project, but am avoiding using it because of this odd dependency. I would very much like to use it, and am happy to attempt provide one of the previous options as a PR!

**Comment by MisterDA** [comment]
Hi again !
I'm rewriting the script, dropping the "odd dependencies". I'll get rid of getoptex and the ini parser. The last one started from a good intention but in the end it isn't very practical. I had an idea to replace it.

The script already knows which version of lua the project uses with this short snippet. The output is stored in a Bash variable.
```lua
f = loadfile("conf.lua");
t, love = {window = {}, modules = {}}, {};
f();
love.conf(t);
t.version = t.version or "";
print(t.version)
```

This can be extended. Would it be better to store the configuration in the `conf.lua` file ? I think it's better to store the variables in a separate function, but if it is polluting too much the global space, a separate file might be more suited.
```lua
function love_release(t)
    t.package.name = "HL3"
    t.windows.release = true
    t.debian.maintainer = "Gabe"
    -- and so on
end
```

**Comment by Positive07** [comment]
Well what about using the same `love.conf` function? 
That way it doesnt contaminate the Global environment, just the `t` table.

Be careful though, since you cant make new tables (that is `t.package.name` wouldnt be possible) because when LÖVE loads it, it will crash.

```lua
love.conf = function (t)
    --Your usual configuration
    t.version = "0.9.2"
    t.package_name = "HL3"
    t.os = {"Window", "Debian", "Android"} --Didnt use release because that is a key in 0.8.0
    t.author = "Positive07" --Used author because that is also a valid key in 0.8.0 and we can use it for this poupose too
end
```

Also try to reuse the info more! For example the backage name can be the same for Debian, Android and Mac with no problem.

So what do you say?

**Comment by MisterDA** [comment]
> Be careful though, since you cant make new tables (that is t.package.name wouldnt be possible) because when LÖVE loads it, it will crash.

I just experienced it :smile: That's why I proposed another function, so the table passed by argument could already be filled and save the user from creating a table (you don't create `t.window`).

Of course the info can be reused, and we can use standard fields, but I'm not confortable with the idea that love-release parameters would be stored directly in the `t` table. It needs at least some sort of namespace, like a `t.lr` table for instance.

There could also be some sort of inheritance mecanism, like a global "package_name" field, which will be overwritten by specific fields for debian, mac...
Naming the fields and organizing them will come a bit later I think.

**Comment by Positive07** [comment]
I just had the best idea!

```lua
love.conf = function (t, r)
    --t is your standard configuration table
    --r is love-release table :D
end
```

**Comment by MisterDA** [comment]
For now I'll just store the values directly in `t`, I'll see later if it really needs to be splitted. I've taken note of you idea.

Love-release can use the standard `t.version`, `t.identity` (instead of a package name), `t.author` and `t.url` (that were removed).
To release a game, simply add the OS name in the `t.os` table. To overwrite a variable for an OS, make a `t.os[osname]` table instead and overwrite the variable here.

What do you think ? Quite easy and extensible I think !

```lua
function love.conf(t)
    t.identity = "myepicgame"          -- The name of the save directory (string)
                                       -- love-release requires [a-z0-9_] characters. Cannot begin with a number.
    t.version = "0.9.2"                -- The LÖVE version this game was made for (string)
    t.game_version = "0.0.1"           -- The version of your game (string)
    t.icon     = "assets/icons"        -- The path to the executable icons (string)
    t.console = false                  -- Attach a console (boolean, Windows only)
    t.exclude  = {                     -- Files and directories to exclude when zipping (array of string)
        ".gitignore",
        "folder/secretfile" }

    t.name = "My epic Game"            -- The name of the game (string)
    t.author = "Marvin"                -- The name of the author (string)
    t.email = "marvin@myepicgame.com"  -- The email of the author (string)
    t.url = "http://myepicgame.com"    -- The website of the game (string)
    t.description = "This epic game is all about me." -- The description of the game (string)

    -- OS to release your game on. Use a table if you want to overwrite the options, or just the OS name.
    -- Available OS are "windows", "osx", "debian" and "android"
    t.os = {
        windows = {
            x86       = true,
            x64       = true,
            installer = false,
            appid     = nil,
        },
        "osx",
        "debian",
        "android",
    }

    -- t.window.*
    -- t.modules.*
end
```

**Comment by josefnpat** [comment]
@bartbes & @slime73 would be the authority on extending the love.conf

**Comment by Positive07** [comment]
`t.name` could be `t.title`. I'm fine with everything else :smile:
