### ISSUE TITLE
Problems on OSX

### ISSUE THREAD

**Issue by rm-code** [MisterDA/love-release#22]
I used ```make``` and ```sudo make install``` to install love-release, but when I try to run it I get an error saying that getopt and readLink aren't installed on my system (but they are):

![screenshot 2015-08-01 09 55 03](https://cloud.githubusercontent.com/assets/11627131/9021134/949c1d00-3833-11e5-9fb3-a22308de5370.png)

Any ideas how to fix this?

**Comment by MisterDA** [comment]
The thing is that ´GNU getopt´ and ´GNU readlink´ are not installed, you have the OSX/BSD version of them.
GNU getopt can parse long options (like ´--Wversion´), BSD getopt can't. I could make a fallback and use only short options if GNU getopt is not found. 
GNU readlink has way more options that the BSD alternative, and I need them  :/ There are possible bash snippets which can work as fallback, but none are as efficient and complete as GNU readlink. 

This is currently the best way I have found to be sure that the script will execute correctly on GNU and OSX.  So for now, if you want to use love-release you could install Homebrew and get getopt and readlink.
I'll add some more instructions un the README if it is not clear enough.

**Comment by rm-code** [comment]
Thanks for the explanation. I installed gnu getopt and gnu readlink, but they don't replace the osx defaults. Is there a way I can point love-release to the correct command without killing the OSX variant?

**Comment by MisterDA** [comment]
If you have installed them with Homebrew they give you the instructions to do so. Getopt needs to be overided (it should not cause compatibility problems) and love-release will detect greadlink if you choose to use an alias.
I can't test or update love-release until the end of the month. Sorry  !

**Comment by rm-code** [comment]
>This formula is keg-only, which means it was not symlinked into /usr/local.

> OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

This is what Homebrew tells me when I install gnu-getopt.

**Comment by MisterDA** [comment]
Yeah I can understand that. I personnally overwrote getopt because they seemed compatible (GNU supports BSD/OSX, not the contrary), but that may cause problems  :D

I would advice against it, so as a quick-and-dirty solution you can add `alias getopt='/usr/local/bin/getopt'` (or the right path to `GNU getopt`) at the beginning of the main `love-release.sh` script and recompile. This should do the work fine.

If it does not (please tell me), then there is only one use of getopt in the whole script so you can replace the 416th line  : 
`ARGS=$(getopt -o "$OPTIONS" -l "$LONG_OPTIONS" -n 'love-release' -- "$@")`
with
`ARGS=$(/usr/local/bin/getopt -o "$OPTIONS" -l "$LONG_OPTIONS" -n 'love-release' -- "$@")`
(or the right path to `GNU getopt`).

Sorry for the trouble  !

**Comment by rm-code** [comment]
> I would advice against it, so as a quick-and-dirty solution you can add alias getopt='/usr/local/bin/getopt' (or the right path to GNU getopt) at the beginning of the main love-release.sh script and recompile. This should do the work fine.

I did this and it does seem to find the command now (or at least it doesn't give me the "GNU getopt is not installed" error anymore), but now I get the following output when I try to use ```love-release``` in the folder of my game:

```
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/share/love-release/scripts/example.sh: line 40: getoptex: command not found
/usr/bin/love-release: line 220: =false: command not found
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/bin/love-release: line 220: =false: command not found
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/bin/love-release: line 332: ${module^^}: bad substitution
/usr/bin/love-release: line 332: ${module^^}: bad substitution
```

**Comment by MisterDA** [comment]
`/usr/bin/love-release: line 332: ${module^^}: bad substitution`
is caused because OSX is shipped with bash 3, and curly-brace-expansion-thing is a feature of bash 4. Anyway, replacing `module=${module^^}` by `module=$(echo "$module" | tr "[:lower:]" "[:upper:]")` should do the work. I tried to use a bash built-in, but OSX version is just... to old. You could replace it with Homebrew (but you don't have to  :p )

`/usr/share/love-release/scripts/example.sh: line 40: getoptex: command not found`
is caused because an old file from a previous version of love-release became unnecessary but causes errors if still present. So get in the love-release directory and `make && sudo make remove && sudo make install`.

`/usr/bin/love-release: line 220: =false: command not found`
Sadly for this one I'm not sure... But my guess is that it is directly related from the first error, which - if fixed - should not trigger this one.
I think it comes when `conf.lua` is parsed, and there is a problem with the module string or the module is not found.


love-release is not very errors-safe. I mean that compatibility is always a problem, but generally speaking a solvable problems. love-release does not really test user input, or the validity of modules name, string validity, commands return codes... A lot of things it could do.

I don't have a computer right know, I'm answering from my phone hoping that the fixes will work, but it's only temporary and I can't try it myself. Thanks for reporting bugs and more importantly, trying the things by yourself  :)

**Comment by rm-code** [comment]
Okay, looks like it works now:

```
Generating  with LÖVE 0.10.0 for LÖVE...
  adding: CHANGELOG.md (stored 0%)
  adding: conf.lua (deflated 66%)
  adding: lib/ (stored 0%)
  adding: lib/screenmanager/ (stored 0%)
  adding: lib/screenmanager/Readme.md (deflated 57%)
  adding: lib/screenmanager/Screen.lua (deflated 75%)
  adding: lib/screenmanager/ScreenManager.lua (deflated 75%)
  adding: LICENSE (deflated 41%)
  adding: main.lua (deflated 70%)
  adding: README.md (stored 0%)
  adding: releases/ (stored 0%)
  adding: src/ (stored 0%)
  adding: src/actors/ (stored 0%)
  adding: src/actors/actions/ (stored 0%)
  adding: src/actors/actions/Attack.lua (deflated 61%)
  adding: src/actors/actions/OpenDoor.lua (deflated 55%)
  adding: src/actors/actions/SwitchPositions.lua (deflated 67%)
  adding: src/actors/actions/Wait.lua (deflated 50%)
  adding: src/actors/actions/WalkAction.lua (deflated 63%)
  adding: src/actors/Actor.lua (deflated 72%)
  adding: src/actors/Ally.lua (deflated 68%)
  adding: src/actors/Enemy.lua (deflated 67%)
  adding: src/actors/Player.lua (deflated 62%)
  adding: src/Constants.lua (deflated 41%)
  adding: src/Game.lua (deflated 73%)
  adding: src/map/ (stored 0%)
  adding: src/map/Door.lua (deflated 40%)
  adding: src/map/Map.lua (deflated 84%)
  adding: src/map/Tile.lua (deflated 75%)
  adding: src/screens/ (stored 0%)
  adding: src/screens/MainScreen.lua (deflated 68%)
Done !
```
The script itself seems to work fine right now. I still have to test it with a 0.9.2 game and some of the options. Will report here if I run into problems!

**Comment by MisterDA** [comment]
I see a little problem, the directory `releases/` should not be included in the zip... 
Otherwise it seems good.

**Comment by MisterDA** [comment]
GNU getopt manual states that:
> If the environment variable GETOPT_COMPATIBLE is set, or if the first parameter is not an option (does not start with a '-', the first format in the SYNOPSIS), getopt will generate output that is compatible with that of other versions of getopt(1).  It will still do parameter shuffling and recognize optional arguments (see section COMPATIBILITY for more information).

> This version of getopt(1) is written to be as compatible as possible to other versions.  Usually you can just replace them with this version without any modifications, and with some advantages.

> The environment variable GETOPT_COMPATIBLE forces getopt into compatibility mode.  Setting both this environment variable and POSIXLY_CORRECT offers 100% compatibility for 'difficult' programs. Usually, though, neither is needed.


At last here seems to be no problem with replacing OSX/BSD getopt by GNU getopt. If you are really afraid, you can:
- add `GETOPT_COMPATIBLE=` to your shell rc (this will set the variable),
- or add an alias to getopt at the beginning of [love-release.sh](../blob/master/love-release.sh) and recompile.  
If installed with Homebrew, add `alias getopt='/usr/local/bin/getopt'`.

I have also added dependencies check (1a70aa5) in the Makefile, and a note in the README (b5c73fe), so that GNU getopt and GNU readlink are better highlighted as dependencies, as well as Bash 4.
