### ISSUE TITLE
Safely executing conf.lua

### ISSUE THREAD

**Issue by Alloyed** [MisterDA/love-release#27]
Less of an issue and more of a design question:

So love-release loads its configuration from `conf.lua` same as love, but the process can be tripped up by the fact that conf.lua is a normal lua file and literally anything can happen from within it. For example, in my current game I have this preamble

```
require 'rocks' () -- part of loverocks, patches packages.loaders
love.filesystem.setSymlinksEnabled(true)
```

I originally put these in my conf.lua because they feel like appropriately config-like things to do, but neither makes sense outside of the love environment, and since I (maybe) want to ditch rockspecs for a later release of loverocks and just read conf.lua directly too, I feel like maybe there should be a common set of rules for writing "safe" conf.lua files that can be read/written by any sort of program, not just love. I'm imagining a lua module that just defines a config loader/sandbox, a config generator and a bunch of tests.

Sound reasonable?

**Comment by MisterDA** [comment]
I never thought of using conf.lua this way, but I guess you can do anything with it :)
In the Lua rewrite, this is the code of my function to read the configuration: 
(it should be around here [scripts/project.lua#L266](https://github.com/MisterDA/love-release/blob/luarocks/scripts/project.lua#L266))

```lua
--- Read LÖVE config file.
-- @treturn {title,package,loveVersion} LÖVE config table
function P.readConf()
  local file = loadfile("conf.lua")
  if not file then return {} end

  _G.love = {}
  _G.t = {
    window = {},
    modules = {},
    screen = {},
  }
  local love, t = _G.love, _G.t

  file()
  love.conf(t)
  _G.love, _G.t = nil, nil

  return {
    title = t.title,
    package = t.package,
    loveVersion = utils.versionExists(t.version)
  }
end
```

I'm just assuming that there is a `love.conf(t)` function in it and that's all. Of course, if there is code outside of it -in the main chunk- or perhaps code that does other things than setting `t` members, there could be unattended and unwanted side-effects. If there's anything wrong with that function, please tell me.

But why won't you do all your configuration (everything that is not directly LÖVE conf.lua related) in the `love.load()` function ? You could even create another config function that would do all your stuff and call it in the load function.

Anyway, I'm more focused on finishing the biggest parts of love-release, then I'll concentrate on the little (but nice) things like that. And I think your idea is more related with the conf.lua syntax itself, which is LÖVE developers business.

My "common set of rules for writing "safe" conf.lua files that can be read/written by any sort of program, not just love" would be to have only the default `love.conf(t)` function with only access to the `t` table, and put every other bit of code elsewhere.
A sandbox (resetting the `_ENV` before loading the file ?) will certainely break everything. I don't know.
If you write a module for what you have in mind, I'll use it, but I'm not sure I have understood all you meant in your idea to write this module myself.


## How love-release handles it's configuration
I'm joining explanations on how love-release has handled it's configuration.

### INI parser
I tried to add a configuration to love-release, so the user wouldn't have to type the arguments in the CLI. The first format I had was INI and I added a Bash-INI parser. Take a look at the result [conf.ini](https://github.com/MisterDA/love-release/commit/5bbf17401a9eb5acc21608f1aa00ca3ba977c53a).
This works but it isn't very practical.

### conf.lua extended
Then I had the idea to make it in a "cascading" way. You would have global command-line arguments that would override per-platform CLI arguments, that would override global configuration, that would override per-platform configuration, that would (finally) override the script's defaults and system-detected arguments.
This is nicer :) That's when I tried to read the conf.lua file. It gives us this format [https://github.com/MisterDA/love-release/blob/master/conf.lua](conf.lua). I reused settings from older LÖVE versions and added some custom options.

```lua
function love.conf(t)
    t.identity = nil                   -- The name of the save directory (string)
                                       -- love-release requires [a-z0-9_] characters. Cannot begin with a number.
    t.version = "0.9.2"                -- The LÖVE version this game was made for (string)
    t.game_version = nil               -- The version of your game (string)
    t.icon = nil                       -- The path to the executable icons (string)
    t.console = false                  -- Attach a console (boolean, Windows only)

    t.title = "Untitled"               -- The name of the game (string)
    t.author = "Unnamed"               -- The name of the author (string)
    t.email = nil                      -- The email of the author (string)
    t.url = nil                        -- The website of the game (string)
    t.description = nil                -- The description of the game (string)

    -- OS to release your game on. Use a table if you want to overwrite the options, or just the OS name.
    -- Available OS are "love", "windows", "osx", "debian" and "android".
    -- A LÖVE file is created if none is specified.
    t.os = {
        "love",
        windows = {
            x32       = true,
            x64       = true,
            installer = false,
            appid     = nil,
        },
        "osx",
        "debian",
        "android",
    }

    -- t.window.*
    -- t.modules.*
end
```

This is not really standard (with LÖVE conf), but I found it rather efficient. I wonder if the concept is really understandable and if people have used it.

### conf.lua strict
Finally, for my rewrite of love-release in Lua I'm sticking to the default (and current) LÖVE options. I may reimplement the previous behavour, depending on its usefulness or not.
I'm turning this issue in my "how love-release should be configured" problem, but since it's my issue tracker :)

**Comment by MisterDA** [comment]
I am using [loadconf](https://github.com/Alloyed/loadconf) in my development branch. Does it fixes this issue ?

**Comment by Alloyed** [comment]
Sure. If you've got any issues with loadconf at this point it's got its own bugtracker <3

**Comment by shakesoda** [comment]
On the topic of conf.lua's that do more than you may have considered... https://github.com/excessive/ludum-dare-34/blob/master/conf.lua

I don't know if this contributes anything to the discussion, but there are plenty of conf.lua's in the wild which do more than simply define love.conf

**Comment by Positive07** [comment]
I dont think `conf.lua` is a safe file (even though I may have suggested this on the past)

I once made a game that worked both in 0.8.0 and 0.9.2 and used `love.getVersion` and `love._version` variables in order to detect which versiom was being used and thus avoiding the message saying "This game was made for another version"

I have also used `conf.lua` to include luarocks with loverocks which uses some functions that are not even part of LÖVE and may rise errors in the loadconf safe sandboxed environment

I have used `conf.lua` in order to change the error screen even before `love.load` is executed in case there are errors in it (hotswapping functionality and custom error messages)

Other use is changing window's settings based on arguments passed in the command line and found on the global args table

**Comment by MisterDA** [comment]
So love-release should not parse this file and use another config file instead ? If a config file is ever needed

**Comment by Positive07** [comment]
I would suggest so, yes

**Comment by Positive07** [comment]
Why was this closed? @Alloyed
