### ISSUE TITLE
MacOS: Symbol not found: _luaL_openlib

### ISSUE THREAD

**Issue by codecat** [MisterDA/love-release#56]
I get the following error when running love-release on MacOS:

```
/usr/local/bin/lua5.3: /usr/local/share/lua/5.3/luarocks/loader.lua:147: error loading module 'misterda.zip' from file '/usr/local/lib/lua/5.3/misterda/zip.so':
	dlopen(/usr/local/lib/lua/5.3/misterda/zip.so, 6): Symbol not found: _luaL_openlib
  Referenced from: /usr/local/lib/lua/5.3/misterda/zip.so
  Expected in: flat namespace
 in /usr/local/lib/lua/5.3/misterda/zip.so
```

**Comment by codecat** [comment]
This looks relevant: https://github.com/scoder/lupa/issues/95

**Comment by MisterDA** [comment]
This is a bug in lua-zip that I have introduced and hopefully fixed in https://github.com/brimworks/lua-zip/pull/14/commits/4b37e9855e3b8d03ce92ec128aa41e6bbe87d6ce.
I have opened a PR to lua-zip upstream, I have not yet reflected the changes in my fork. If upstream accepts the patch quickly, love-release will switch back to lua-zip, if not I will update my fork and stay with it.
Thanks for the bug-report!
